# Describing the elements of the cluster

version: '2'

services:

  node:
    image: clusterfuck-node
    command: "sh -c \"hostname -i | xargs -I {} clusterfuck-exe slave {} 5000 \""

  master-node:
    image: clusterfuck-node
    command: "sh -c \"hostname -i | xargs -I {} clusterfuck-exe master {} 5000 \""
    depends_on:
      - node
